FROM python:3.12-slim-bookworm

WORKDIR /opt/remnashop

COPY pyproject.toml .
COPY docker-entrypoint.sh .

RUN pip install --no-cache-dir uv && uv sync

ENV UVICORN_RELOAD_ENABLED=true

CMD [ "/bin/sh", "docker-entrypoint.sh" ]